project_id = "hxdrffemnrxklrrfnllo"

[functions.setup-demo-admin]
verify_jwt = false

[functions.seed-platform-admin]
verify_jwt = false

[functions.generate-pda-pdf]
verify_jwt = true

[functions.send-organization-invite]
verify_jwt = false